### PR TITLE
Added ability to change default value for priority and changefreq + tests

### PR DESCRIPTION
**Pull request by ricardofiorani**
Solves #22 and #24

### CODE REVIEW

**Review by erezrokah — CHANGES_REQUESTED** [review]
Thanks @ricardofiorani, nice one. Do you mind updating the README?

**Comment by ricardofiorani** [comment]
@erezrokah I solved the conflicts and updated the README. Please let me know if anything else is needed.

**Review by erezrokah — APPROVED** [review]
Thanks again @ricardofiorani, very nice feature.
I just formatted the readme section to look like the others, removed `failPlugin` as it was no longer used and rename the tests to have a bit more descriptive title

**Comment by ricardofiorani** [comment]
@erezrokah could you please add the label `hacktoberfest-accepted` to this PR ?
https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Pull request merged**
